[package]
name = "smilefetch"
version = "0.3.0"
edition = "2021"

[dependencies]
whoami = "1.2.1"
sys-info = "0.9.1"
proc_getter = "0.0.3"
pretty-bytes = "0.2.2"
colored = "2.0.0"
clap = { version = "3.1.6", features = ["derive"] }
