[package]
name = "smilefetch"
version = "0.3.1"
edition = "2021"

[dependencies]
futures = "0.3"
whoami = "1.2"
sysinfo = "0.24"
etc-passwd = "0.1"

pretty-bytes = "0.2"
colored = "2.0"
clap = { version = "3.1", features = ["derive"] }
